export const enneagramQuestions = [
    { "id": 1, "text": { "fr": "Je prévois la prochaine aventure avant que celle en cours soit terminée.", "en": "I plan my next adventure before the current one is finished." }, "type": 7 },
    { "id": 2, "text": { "fr": "Je m'abstiens souvent d'agir, car j'ai peur d'être débordé.", "en": "I often refrain from acting because I fear being overwhelmed." }, "type": 9 },
    { "id": 3, "text": { "fr": "Je suis trop sévère envers moi-même et envers les autres.", "en": "I am too strict with myself and others." }, "type": 1 },
    { "id": 4, "text": { "fr": "Le succès, le prestige et la reconnaissance comptent vraiment pour moi.", "en": "Success, prestige, and recognition really matter to me." }, "type": 3 },
    { "id": 5, "text": { "fr": "J'aime prendre soin des gens et ça me fait du bien.", "en": "I like taking care of people and it makes me feel good." }, "type": 2 },
    { "id": 6, "text": { "fr": "Je ne suis pas facilement déprimé, voire pas du tout.", "en": "I am not easily depressed, if at all." }, "type": 7 },
    { "id": 7, "text": { "fr": "Je suis plus sensible que la plupart des gens, parfois le monde me semble trop sévère.", "en": "I am more sensitive than most people; sometimes the world seems too harsh." }, "type": 4 },
    { "id": 8, "text": { "fr": "Je veux gagner l'approbation de ceux qui sont au pouvoir, parfois même si je ne les aime pas vraiment.", "en": "I want to win the approval of those in power, sometimes even if I don't really like them." }, "type": 3 },
    { "id": 9, "text": { "fr": "J'ai tendance à faire confiance à la plupart des gens.", "en": "I tend to trust most people." }, "type": 9 },
    { "id": 10, "text": { "fr": "Dans la plupart des relations intimes, je donne plus que je prends.", "en": "In most intimate relationships, I give more than I take." }, "type": 2 },
    { "id": 11, "text": { "fr": "Je ne vois pas beaucoup d'intérêt à me vautrer dans des émotions négatives. Quand je commence à me sentir anxieux, j'ai tendance à me jeter dans des activités distrayantes.", "en": "I don't see much point in wallowing in negative emotions. When I start feeling anxious, I tend to dive into distracting activities." }, "type": 7 },
    { "id": 12, "text": { "fr": "Je pourrais probablement avoir un peu plus d'ambition.", "en": "I could probably have a bit more ambition." }, "type": 9 },
    { "id": 13, "text": { "fr": "Je suis assez dominateur.", "en": "I am quite dominating." }, "type": 8 },
    { "id": 14, "text": { "fr": "Je suis toujours conscient de ce qui doit être corrigé.", "en": "I am always aware of what needs to be fixed." }, "type": 1 },
    { "id": 15, "text": { "fr": "Je suis sceptique, méfiant et dubitatif.", "en": "I am skeptical, suspicious, and doubtful." }, "type": 6 },
    { "id": 16, "text": { "fr": "Je suis mal à l'aise quand les gens veulent une réponse émotionnelle de moi.", "en": "I am uncomfortable when people want an emotional response from me." }, "type": 5 },
    { "id": 17, "text": { "fr": "C'est difficile pour moi de mettre mes sentiments de côté, même pour accomplir un travail.", "en": "It is difficult for me to put my feelings aside, even to get a job done." }, "type": 4 },
    { "id": 18, "text": { "fr": "Il est important pour moi que je sois admiré par d'autres - et beaucoup de gens m'admirent.", "en": "It is important for me to be admired by others - and many do admire me." }, "type": 3 },
    { "id": 19, "text": { "fr": "Je ne crains pas de prendre un risque; j'aime vraiment l'adversité.", "en": "I am not afraid to take risks; I actually enjoy adversity." }, "type": 8 },
    { "id": 20, "text": { "fr": "Votre bonheur et vos sentiments sont de votre responsabilité, pas la mienne.", "en": "Your happiness and feelings are your responsibility, not mine." }, "type": 5 },
    { "id": 21, "text": { "fr": "Je suis plus organisé que la plupart des gens.", "en": "I am more organized than most people." }, "type": 1 },
    { "id": 22, "text": { "fr": "J'évite d'exprimer des émotions fortes.", "en": "I avoid expressing strong emotions." }, "type": 5 },
    { "id": 23, "text": { "fr": "Même si c'est souvent irrationnel, je m'inquiète parfois de ce que les gens peuvent dire de moi dans mon dos.", "en": "Even if it's often irrational, I sometimes worry about what people might say behind my back." }, "type": 6 },
    { "id": 24, "text": { "fr": "Je suis un vrai romantique.", "en": "I am a true romantic." }, "type": 4 },
    { "id": 25, "text": { "fr": "Il m'est facile d'accepter les autres, et eux semblent à l'aise avec moi parce que je ne les juge pas.", "en": "It is easy for me to accept others, and they seem comfortable with me because I don't judge them." }, "type": 9 },
    { "id": 26, "text": { "fr": "Les relations personnelles sont de loin la chose la plus importante dans ma vie.", "en": "Personal relationships are by far the most important thing in my life." }, "type": 2 },
    { "id": 27, "text": { "fr": "Pour le meilleur ou pour le pire, je me compare à d'autres pour évaluer ma façon de faire.", "en": "For better or worse, I compare myself to others to evaluate how I am doing." }, "type": 3 },
    { "id": 28, "text": { "fr": "Je tiens à observer et penser, sans me révéler, avant de passer à l'action.", "en": "I prefer to observe and think, without revealing myself, before taking action." }, "type": 5 },
    { "id": 29, "text": { "fr": "Je m'ennuie plus facilement que la plupart des gens, je suis toujours en quête de nouvelles expériences.", "en": "I get bored more easily than most people; I am always seeking new experiences." }, "type": 7 },
    { "id": 30, "text": { "fr": "Je donne plus d'amour que la plupart des gens.", "en": "I give more love than most people." }, "type": 2 },
    { "id": 31, "text": { "fr": "Je suis très individualiste.", "en": "I am very individualistic." }, "type": 4 },
    { "id": 32, "text": { "fr": "Je suis assez discret et facile à vivre.", "en": "I am quite discreet and easy-going." }, "type": 9 },
    { "id": 33, "text": { "fr": "Je suis plus formaliste que la plupart des gens.", "en": "I am more formal than most people." }, "type": 1 },
    { "id": 34, "text": { "fr": "J'ai des talents pour créer des réseaux de connaissances.", "en": "I am talented at networking." }, "type": 3 },
    { "id": 35, "text": { "fr": "Les règles m'agacent.", "en": "Rules annoy me." }, "type": 7 },
    { "id": 36, "text": { "fr": "Même si je suis très fidèle, j'ai souvent peur que les autres ne soient pas fidèles envers moi.", "en": "Even though I am very loyal, I often fear that others are not loyal to me." }, "type": 6 },
    { "id": 37, "text": { "fr": "Je suis plus capricieux que la plupart mais c'est parce que mes sentiments sont si forts.", "en": "I am moodier than most, but that's because my feelings are so strong." }, "type": 4 },
    { "id": 38, "text": { "fr": "Généralement, personne n'aime subir l'intrusion de quelqu'un, mais moi, je déteste carrément ça!", "en": "Generally, nobody likes intrusion, but I absolutely hate it!" }, "type": 5 },
    { "id": 39, "text": { "fr": "Les gens sont attirés par moi parce que je les impressionne.", "en": "People are drawn to me because I impress them." }, "type": 3 },
    { "id": 40, "text": { "fr": "Mes opinions sont assez fortes et peuvent parfois intimider les gens.", "en": "My opinions are quite strong and can sometimes intimidate people." }, "type": 8 },
    { "id": 41, "text": { "fr": "J'essaie de me rapprocher de gens en étant généreux de mon temps et mon énergie.", "en": "I try to get closer to people by being generous with my time and energy." }, "type": 2 },
    { "id": 42, "text": { "fr": "Je suis souvent contrarié quand je vois des gens qui font un travail négligé.", "en": "I am often annoyed when I see people doing sloppy work." }, "type": 1 },
    { "id": 43, "text": { "fr": "Je n'aime pas l'engagement. Qui veut se laisser enfermer dans quelque chose, surtout si quelque chose de mieux se présente?", "en": "I don't like commitment. Who wants to be locked into something, especially if something better comes along?" }, "type": 7 },
    { "id": 44, "text": { "fr": "Je fais ce que les autres veulent, sauf si j'ai une très forte envie, ce que je n'ai généralement pas.", "en": "I do what others want, unless I have a very strong desire, which I usually don't." }, "type": 9 },
    { "id": 45, "text": { "fr": "Je suis à l'affût de tout ce qui pourrait être dangereux et je suis très attentif à la sécurité.", "en": "I am on the lookout for anything dangerous and am very safety-concious." }, "type": 6 },
    { "id": 46, "text": { "fr": "Lorsque je prends une décision, je me demande souvent : 'Quelle option donnera le maximum de plaisir?'.", "en": "When I make a decision, I often ask myself: 'Which option will give the most pleasure?'." }, "type": 7 },
    { "id": 47, "text": { "fr": "J'ai tendance à éviter les conflits.", "en": "I tend to avoid conflict." }, "type": 9 },
    { "id": 48, "text": { "fr": "Parfois, j'ai beaucoup trop tendance à essayer d'aider les gens.", "en": "Sometimes I try to help people way too much." }, "type": 2 },
    { "id": 49, "text": { "fr": "Il est important pour moi d'avoir un sentiment d'appartenance.", "en": "It is important for me to have a sense of belonging." }, "type": 6 },
    { "id": 50, "text": { "fr": "Je suis compétitif et ambitieux, mais je ne crois pas être acharné.", "en": "I am competitive and ambitious, but I don't think I'm cutthroat." }, "type": 3 },
    { "id": 51, "text": { "fr": "Je suis attiré par l'intensité émotionnelle et n'ai pas peur d'en explorer les profondeurs.", "en": "I am drawn to emotional intensity and am not afraid to explore its depths." }, "type": 4 },
    { "id": 52, "text": { "fr": "Je vois la vie comme une lutte que j'ai l'intention de gagner.", "en": "I see life as a struggle that I intend to win." }, "type": 8 },
    { "id": 53, "text": { "fr": "Je suis méticuleux et minutieux, même sur des détails que d'autres personnes jugent mineurs.", "en": "I am meticulous and thorough, even about details others find minor." }, "type": 1 },
    { "id": 54, "text": { "fr": "Si je ne fais pas attention, je peux trop m'isoler des autres.", "en": "If I'm not careful, I can isolate myself too much from others." }, "type": 5 },
    { "id": 55, "text": { "fr": "Je détiens un contrôle serré sur mon humeur.", "en": "I keep a tight control on my mood." }, "type": 8 },
    { "id": 56, "text": { "fr": "Pour faire face à la peur que j'ai toujours, je suis aussi gentil et chaleureux que possible envers tout le monde.", "en": "To cope with the fear I always have, I am as kind and warm as possible to everyone." }, "type": 6 },
    { "id": 57, "text": { "fr": "Je remets souvent au lendemain.", "en": "I often procrastinate." }, "type": 9 },
    { "id": 58, "text": { "fr": "J'aime beaucoup de gens, et beaucoup de gens m'aiment.", "en": "I like many people, and many people like me." }, "type": 2 },
    { "id": 59, "text": { "fr": "Je suis indifférent à la manière dont la plupart des gens se sentent.", "en": "I am indifferent to how most people feel." }, "type": 5 },
    { "id": 60, "text": { "fr": "J'aime regarder ce qui est de bon goût, mais je pense que je peux aussi apprécier la beauté simple des choses ordinaires.", "en": "I like looking at tasteful things, but I think I can also appreciate the simple beauty of ordinary things." }, "type": 4 },
    { "id": 61, "text": { "fr": "Il est important pour moi de savoir où je vais et de planifier les étapes à suivre pour y arriver.", "en": "It is important for me to know where I am going and plan the steps to get there." }, "type": 1 },
    { "id": 62, "text": { "fr": "Je ne me laisse pas abattre facilement par mes émotions.", "en": "I don't let my emotions get me down easily." }, "type": 8 },
    { "id": 63, "text": { "fr": "Quand des gens sont sous mon aile, ils savent que je les protégerai et veillerai à ce qu'ils aient ce dont ils ont besoin.", "en": "When people are under my wing, they know I will protect them and ensure they have what they need." }, "type": 2 },
    { "id": 64, "text": { "fr": "Mon sentiment de sécurité est directement lié à mes relations étroites.", "en": "My sense of security is directly tied to my close relationships." }, "type": 6 },
    { "id": 65, "text": { "fr": "Je me sens souvent inquiet de ce que les autres pourraient penser de moi.", "en": "I often worry about what others might think of me." }, "type": 3 },
    { "id": 66, "text": { "fr": "Je me perds parfois dans mes fantasmes.", "en": "I sometimes get lost in my fantasies." }, "type": 4 },
    { "id": 67, "text": { "fr": "J'ai tendance à éviter les gens qui essaient de me dire quoi faire.", "en": "I tend to avoid people who try to tell me what to do." }, "type": 5 },
    { "id": 68, "text": { "fr": "Mettre l'accent sur les défauts des gens ou sur les événements négatifs ne permet pas d'avoir des relations harmonieuses. Je préfère voir les aspects positifs de chacun et de la vie.", "en": "Focusing on people's flaws or negative events doesn't make for harmonious relationships. I prefer to see the positive aspects of everyone and life." }, "type": 9 },
    { "id": 69, "text": { "fr": "Je suis bon pour faire avancer les choses.", "en": "I am good at getting things done." }, "type": 3 },
    { "id": 70, "text": { "fr": "Je ne perds presque jamais le contrôle de moi-même.", "en": "I almost never lose self-control." }, "type": 8 },
    { "id": 71, "text": { "fr": "Si quelque chose ne va pas comme je le voudrais, je peux trouver quelque chose de bénéfique à ce sujet.", "en": "If something doesn't go my way, I can find something beneficial about it." }, "type": 7 },
    { "id": 72, "text": { "fr": "Je veux être remarqué, mais ça me met également mal à l'aise.", "en": "I want to be noticed, but it also makes me uncomfortable." }, "type": 4 },
    { "id": 73, "text": { "fr": "Le changement - que ce soit à un nouvel emploi ou nouvelle école, me rend plus anxieux que la plupart des gens.", "en": "Change - whether a new job or school - makes me more anxious than most people." }, "type": 6 },
    { "id": 74, "text": { "fr": "Je ne peux pas me reposer tant que le travail n'est pas fini.", "en": "I cannot rest until the work is finished." }, "type": 1 },
    { "id": 75, "text": { "fr": "Je suis assez dur.", "en": "I am quite tough." }, "type": 8 },
    { "id": 76, "text": { "fr": "Je déborde d'idées. Pour chaque problème, je peux imaginer au moins 10 solutions.", "en": "I am overflowing with ideas. For every problem, I can imagine at least 10 solutions." }, "type": 7 },
    { "id": 77, "text": { "fr": "La plupart des gens ne savent pas que je suis vraiment sensible, car j'ai tendance à cacher mes émotions.", "en": "Most people don't know I'm actually sensitive, because I tend to hide my emotions." }, "type": 4 },
    { "id": 78, "text": { "fr": "Je ne suis pas un frimeur, en fait, je suis peut-être trop modeste.", "en": "I'm not a show-off; in fact, I might be too modest." }, "type": 9 },
    { "id": 79, "text": { "fr": "Je ne le montre pas, mais si je suis avec quelqu'un qui est aussi unique que je suis, je suis un peu jaloux.", "en": "I don't show it, but if I'm with someone as unique as I am, I get a bit jealous." }, "type": 4 },
    { "id": 80, "text": { "fr": "Il est important pour moi de gagner le respect des autres.", "en": "It is important for me to earn the respect of others." }, "type": 3 },
    { "id": 81, "text": { "fr": "Les autres ont beaucoup plus besoin de mon aide, que moi j'ai besoin de la leur.", "en": "Others need my help much more than I need theirs." }, "type": 2 },
    { "id": 82, "text": { "fr": "On me reproche parfois de manquer de tact, mais je pense qu'il est important de dire la vérité.", "en": "I am sometimes accused of lacking tact, but I think it is important to tell the truth." }, "type": 5 },
    { "id": 83, "text": { "fr": "J'apparais généralement calme voire serein, même quand je subis une énorme pression.", "en": "I generally appear calm or even serene, even under huge pressure." }, "type": 9 },
    { "id": 84, "text": { "fr": "J'ai une envie irrésistible de faire les choses bien, même si ce n'est pas rentable.", "en": "I have a compelling urge to do things right, even if it isn't profitable." }, "type": 1 },
    { "id": 85, "text": { "fr": "Je perds souvent ma concentration car mon attention tend à s'éparpiller.", "en": "I often lose focus because my attention tends to scatter." }, "type": 7 },
    { "id": 86, "text": { "fr": "Prendre des décisions importantes me demande beaucoup de temps et d'efforts et souvent je doute après coup.", "en": "Making important decisions takes me a lot of time and effort, and I often doubt them afterwards." }, "type": 6 },
    { "id": 87, "text": { "fr": "Je suis plus dramatique que les autres.", "en": "I am more dramatic than others." }, "type": 4 },
    { "id": 88, "text": { "fr": "Les gens me voient comme une personne chaleureuse et sympathique.", "en": "People see me as a warm and friendly person." }, "type": 2 },
    { "id": 89, "text": { "fr": "J'ai tendance à ne pas envisager de demander l'aide des autres, même de ceux que j'aime.", "en": "I tend not to consider asking for help from others, even those I love." }, "type": 5 },
    { "id": 90, "text": { "fr": "J'aime trop m'amuser pour être discipliné.", "en": "I like having fun too much to be disciplined." }, "type": 7 },
    { "id": 91, "text": { "fr": "C'est difficile pour moi de rester passionné et concentré.", "en": "It is hard for me to stay passionate and focused." }, "type": 9 },
    { "id": 92, "text": { "fr": "Souvent, les gens ne sont pas ce qu'ils affichent, c'est pourquoi je me méfie vraiment de leurs motivations.", "en": "People often aren't what they seem, which is why I'm really suspicious of their motives." }, "type": 6 },
    { "id": 93, "text": { "fr": "En général je n'aime pas rester très longtemps sur une tâche de très longue durée. Je m'agite, et je veux passer à autre chose.", "en": "Generally I don't like staying on a very long task for too long. I get restless and want to move on." }, "type": 7 },
    { "id": 94, "text": { "fr": "J'ai tendance à fuir la réalité dans un monde fantasmé et idéalisé.", "en": "I tend to escape reality into a fantasized and idealized world." }, "type": 4 },
    { "id": 95, "text": { "fr": "Je ne suis pas à l'aise avec des révélations me concernant.", "en": "I am not comfortable with revelations about myself." }, "type": 5 },
    { "id": 96, "text": { "fr": "Si la vie c'est donner et prendre, donner de l'amour est la chose la plus importante dans ma vie.", "en": "If life is give and take, giving love is the most important thing in my life." }, "type": 2 },
    { "id": 97, "text": { "fr": "Même si je ne sais pas ce que je fais, je peux au moins faire semblant.", "en": "Even if I don't know what I'm doing, I can at least fake it." }, "type": 3 },
    { "id": 98, "text": { "fr": "Ma tendance à dire aux gens ce qui ne va pas et ce qu'ils devraient faire, les agace parfois.", "en": "My tendency to tell people what's wrong and what they should do sometimes annoys them." }, "type": 1 },
    { "id": 99, "text": { "fr": "J'ai plus d'énergie et de force que la plupart des gens.", "en": "I have more energy and strength than most people." }, "type": 8 },
    { "id": 100, "text": { "fr": "J'ai tendance à avoir des sentiments mitigés au sujet de nombreuses personnes.", "en": "I tend to have mixed feelings about many people." }, "type": 6 },
    { "id": 101, "text": { "fr": "Je préfère improviser, alors j'ai tendance à entamer les choses, avant d'avoir réfléchi au résultat.", "en": "I prefer to improvise, so I tend to start things before thinking about the result." }, "type": 7 },
    { "id": 102, "text": { "fr": "L'esthétique de mon environnement a une forte influence sur mon humeur.", "en": "The aesthetics of my environment strongly influence my mood." }, "type": 4 },
    { "id": 103, "text": { "fr": "Je ferai ce qu'il faut pour réussir.", "en": "I will do whatever it takes to succeed." }, "type": 3 },
    { "id": 104, "text": { "fr": "J'ai l'habitude de m'endormir facilement et peut même faire une sieste quand je suis stressé.", "en": "I usually fall asleep easily and can even nap when I'm stressed." }, "type": 9 },
    { "id": 105, "text": { "fr": "Je suis doué pour adopter une vue d'ensemble, mais je n'ai pas de patience avec les détails.", "en": "I am good at seeing the big picture, but I have no patience for details." }, "type": 5 },
    { "id": 106, "text": { "fr": "Parfois, je ne sais pas ce que je ressens jusqu'à ce que j'aie l'occasion d'y réfléchir.", "en": "Sometimes I don't know how I feel until I have a chance to think about it." }, "type": 4 },
    { "id": 107, "text": { "fr": "Je suis fier du fait que de nombreuses personnes dépendent de moi.", "en": "I am proud that many people depend on me." }, "type": 8 },
    { "id": 108, "text": { "fr": "On me dit que je suis perfectionniste et je suppose que c'est vrai.", "en": "I am told I am a perfectionist and I guess it's true." }, "type": 1 },
    { "id": 109, "text": { "fr": "J'aime me rappeler le passé, même si c'est un peu mélancolique.", "en": "I like remembering the past, even if it's a bit melancholic." }, "type": 4 },
    { "id": 110, "text": { "fr": "Je suis très sensible à l'effet que je fais sur les autres et j'essaie de contrôler l'image que je donne de moi.", "en": "I am very sensitive to the effect I have on others and try to control the image I project." }, "type": 3 },
    { "id": 111, "text": { "fr": "Bien que je tienne à mes relations intimes, je me sens souvent plus en harmonie avec moi-même quand je suis seul.", "en": "Although I value my intimate relationships, I often feel more at peace when I am alone." }, "type": 5 },
    { "id": 112, "text": { "fr": "Quand j'arrive, la fête commence.", "en": "When I arrive, the party starts." }, "type": 7 },
    { "id": 113, "text": { "fr": "Je me fous de la morale, mais j'ai mon propre sens de l'intégrité.", "en": "I don't care about morality, but I have my own sense of integrity." }, "type": 8 },
    { "id": 114, "text": { "fr": "Je cherche parfois trop d'attention.", "en": "I sometimes seek too much attention." }, "type": 4 },
    { "id": 115, "text": { "fr": "Je travaille si dur pour les autres que je ne me soucie pas vraiment de prendre soin de moi.", "en": "I work so hard for others that I don't really care about taking care of myself." }, "type": 2 },
    { "id": 116, "text": { "fr": "Mon instinct de survie me garde en sécurité.", "en": "My survival instinct keeps me safe." }, "type": 6 },
    { "id": 117, "text": { "fr": "Je me compare aux autres pour savoir si je suis 'à la hauteur'.", "en": "I compare myself to others to see if I 'measure up'." }, "type": 3 },
    { "id": 118, "text": { "fr": "J'ai besoin de me sentir valorisé.", "en": "I need to feel valued." }, "type": 2 },
    { "id": 119, "text": { "fr": "Je m'inquiète rarement de ce qui pourrait arriver.", "en": "I rarely worry about what might happen." }, "type": 7 },
    { "id": 120, "text": { "fr": "Je sais comment gérer les crises de façon efficace et décisive.", "en": "I know how to handle crises effectively and decisively." }, "type": 8 },
    { "id": 121, "text": { "fr": "Je prévois la prochaine aventure avant que celle en cours soit terminée.", "en": "I plan the next adventure before the current one is finished." }, "type": 7 },
    { "id": 122, "text": { "fr": "Je m'abstiens souvent d'agir, car j'ai peur d'être débordé.", "en": "I often refrain from acting because I fear being overwhelmed." }, "type": 6 },
    { "id": 123, "text": { "fr": "Je suis trop sévère envers moi-même et envers les autres.", "en": "I am too strict with myself and others." }, "type": 1 },
    { "id": 124, "text": { "fr": "Le succès, le prestige et la reconnaissance comptent vraiment pour moi.", "en": "Success, prestige, and recognition really matter to me." }, "type": 3 },
    { "id": 125, "text": { "fr": "J'aime prendre soin des gens et ça me fait du bien.", "en": "I like taking care of people and it makes me feel good." }, "type": 2 },
    { "id": 126, "text": { "fr": "Je ne suis pas facilement déprimé, voire pas du tout.", "en": "I am not easily depressed, if at all." }, "type": 9 }
];

export const mbtiQuestions = [
    { "id": 1, "text": { "fr": "Vous vous faites fréquemment de nouveaux amis.", "en": "You frequently make new friends." }, "dimension": "EI", "direction": 1 },
    { "id": 2, "text": { "fr": "Les idées complexes et novatrices vous enthousiasment plus que les idées simples et directes.", "en": "Complex and novel ideas excite you more than simple and straightforward ones." }, "dimension": "SN", "direction": 1 },
    { "id": 3, "text": { "fr": "Vous vous laissez plus facilement convaincre par des émotions que par des arguments factuels.", "en": "You are more easily persuaded by emotions than by factual arguments." }, "dimension": "TF", "direction": 1 },
    { "id": 4, "text": { "fr": "Vos espaces de vie et de travail sont propres et organisés.", "en": "Your living and work spaces are clean and organized." }, "dimension": "JP", "direction": 1 },
    { "id": 5, "text": { "fr": "Vous restez calme même sous une forte pression.", "en": "You stay calm even under high pressure." }, "dimension": "AT", "direction": 1 },
    { "id": 6, "text": { "fr": "L’idée de réseauter avec des étrangers vous intimide.", "en": "The idea of networking with strangers intimidates you." }, "dimension": "EI", "direction": -1 },
    { "id": 7, "text": { "fr": "Vous planifiez et accomplissez vos tâches bien avant la date limite.", "en": "You plan and complete your tasks well before the deadline." }, "dimension": "JP", "direction": 1 },
    { "id": 8, "text": { "fr": "Les histoires des gens vous touchent plus que les chiffres ou les données.", "en": "Peoples stories touch you more than numbers or data." }, "dimension": "TF", "direction": 1 },
    { "id": 9, "text": { "fr": "Vous aimez utiliser des outils de gestion comme des calendriers ou des listes.", "en": "You like using management tools like calendars or lists." }, "dimension": "JP", "direction": 1 },
    { "id": 10, "text": { "fr": "Une petite erreur peut vous faire douter de vos capacités.", "en": "A small mistake can make you doubt your abilities." }, "dimension": "AT", "direction": -1 },
    { "id": 11, "text": { "fr": "Vous n'avez aucun mal à engager une conversation avec quelqu'un d'intéressant.", "en": "You have no trouble striking up a conversation with someone interesting." }, "dimension": "EI", "direction": 1 },
    { "id": 12, "text": { "fr": "Vous n’aimez pas discuter des interprétations d’œuvres créatives.", "en": "You dislike discussing interpretations of creative works." }, "dimension": "SN", "direction": -1 },
    { "id": 13, "text": { "fr": "Vous privilégiez les faits plutôt que les sentiments pour déterminer une ligne de conduite.", "en": "You value facts over feelings when determining a course of action." }, "dimension": "TF", "direction": -1 },
    { "id": 14, "text": { "fr": "Vous laissez souvent la journée se dérouler sans planning.", "en": "You often let the day unfold without a plan." }, "dimension": "JP", "direction": -1 },
    { "id": 15, "text": { "fr": "Vous ne vous souciez pas trop de faire bonne impression.", "en": "You don't worry too much about making a good impression." }, "dimension": "AT", "direction": 1 },
    { "id": 16, "text": { "fr": "Vous appréciez participer à des activités en équipe.", "en": "You enjoy participating in team activities." }, "dimension": "EI", "direction": 1 },
    { "id": 17, "text": { "fr": "Vous aimez expérimenter des approches nouvelles et non testées.", "en": "You like experimenting with new and untested approaches." }, "dimension": "SN", "direction": 1 },
    { "id": 18, "text": { "fr": "Vous attachez plus d'importance à la sensibilité qu'à l'honnêteté.", "en": "You value sensitivity more than honesty." }, "dimension": "TF", "direction": 1 },
    { "id": 19, "text": { "fr": "Vous êtes en quête de nouvelles expériences et connaissances.", "en": "You are seeking new experiences and knowledge." }, "dimension": "SN", "direction": 1 },
    { "id": 20, "text": { "fr": "Vous avez tendance à vous inquiéter de l'avenir.", "en": "You tend to worry about the future." }, "dimension": "AT", "direction": -1 },
    { "id": 21, "text": { "fr": "Vous appréciez davantage les passe-temps solitaires que ceux en groupe.", "en": "You enjoy solitary hobbies more than group ones." }, "dimension": "EI", "direction": -1 },
    { "id": 22, "text": { "fr": "Vous ne vous voyez pas écrire de la fiction.", "en": "You cannot see yourself writing fiction." }, "dimension": "SN", "direction": -1 },
    { "id": 23, "text": { "fr": "Vous préférez des décisions efficaces, même si elles ignorent des aspects émotionnels.", "en": "You prefer efficient decisions, even if they ignore emotional aspects." }, "dimension": "TF", "direction": -1 },
    { "id": 24, "text": { "fr": "Vous vous acquittez des tâches avant de vous détendre.", "en": "You complete tasks before relaxing." }, "dimension": "JP", "direction": 1 },
    { "id": 25, "text": { "fr": "En cas de désaccord, vous défendez votre point de vue au détriment des sentiments d’autrui.", "en": "In a disagreement, you defend your point of view regardless of others' feelings." }, "dimension": "TF", "direction": -1 },
    { "id": 26, "text": { "fr": "Vous attendez souvent que les autres se présentent en premier dans les réunions sociales.", "en": "You often wait for others to introduce themselves first at social gatherings." }, "dimension": "EI", "direction": -1 },
    { "id": 27, "text": { "fr": "Votre humeur peut changer très rapidement.", "en": "Your mood can change very quickly." }, "dimension": "AT", "direction": -1 },
    { "id": 28, "text": { "fr": "Vous ne vous laissez pas facilement influencer par des arguments émotionnels.", "en": "You are not easily swayed by emotional arguments." }, "dimension": "TF", "direction": -1 },
    { "id": 29, "text": { "fr": "Vous faites souvent les choses à la dernière minute.", "en": "You often do things at the last minute." }, "dimension": "JP", "direction": -1 },
    { "id": 30, "text": { "fr": "Vous aimez débattre de dilemmes éthiques.", "en": "You enjoy debating ethical dilemmas." }, "dimension": "SN", "direction": 1 },
    { "id": 31, "text": { "fr": "Vous préférez être entouré plutôt que seul.", "en": "You prefer to be around people rather than alone." }, "dimension": "EI", "direction": 1 },
    { "id": 32, "text": { "fr": "Vous perdez intérêt quand la discussion devient trop théorique.", "en": "You lose interest when the discussion becomes too theoretical." }, "dimension": "SN", "direction": -1 },
    { "id": 33, "text": { "fr": "Vous suivez généralement votre cœur en cas de conflit entre les faits et les sentiments.", "en": "You usually follow your heart where facts and feelings conflict." }, "dimension": "TF", "direction": 1 },
    { "id": 34, "text": { "fr": "Vous avez du mal à maintenir un planning cohérent.", "en": "You struggle to maintain a consistent schedule." }, "dimension": "JP", "direction": -1 },
    { "id": 35, "text": { "fr": "Vous remettez rarement en question vos choix.", "en": "You rarely second-guess your choices." }, "dimension": "AT", "direction": 1 },
    { "id": 36, "text": { "fr": "Vos amis vous décriraient comme extraverti et enjoué.", "en": "Your friends would describe you as extroverted and lively." }, "dimension": "EI", "direction": 1 },
    { "id": 37, "text": { "fr": "Vous êtes attiré par diverses formes d'expression créative.", "en": "You are drawn to various forms of creative expression." }, "dimension": "SN", "direction": 1 },
    { "id": 38, "text": { "fr": "Vous basez vos choix sur des faits objectifs plutôt que sur des sentiments.", "en": "You base your choices on objective facts rather than feelings." }, "dimension": "TF", "direction": -1 },
    { "id": 39, "text": { "fr": "Vous aimez faire des listes de choses à faire.", "en": "You like to make to-do lists." }, "dimension": "JP", "direction": 1 },
    { "id": 40, "text": { "fr": "Vous manquez rarement de confiance en vous.", "en": "You rarely lack self-confidence." }, "dimension": "AT", "direction": 1 },
    { "id": 41, "text": { "fr": "Vous évitez de passer des appels téléphoniques.", "en": "You avoid making phone calls." }, "dimension": "EI", "direction": -1 },
    { "id": 42, "text": { "fr": "Vous aimez découvrir de nouveaux points de vue.", "en": "You love discovering new points of view." }, "dimension": "SN", "direction": 1 },
    { "id": 43, "text": { "fr": "Vous établissez facilement des liens avec des personnes que vous venez de rencontrer.", "en": "You easily connect with people you've just met." }, "dimension": "EI", "direction": 1 },
    { "id": 44, "text": { "fr": "Si vos projets sont compromis, votre priorité est de reprendre le fil au plus vite.", "en": "If your plans are interrupted, your top priority is to get back on track ASAP." }, "dimension": "JP", "direction": 1 },
    { "id": 45, "text": { "fr": "Vous êtes encore préoccupé par des erreurs passées.", "en": "You are still bothered by past mistakes." }, "dimension": "AT", "direction": -1 },
    { "id": 46, "text": { "fr": "Vous n'aimez pas discuter de théories sur l'avenir du monde.", "en": "You dislike discussing theories about the future of the world." }, "dimension": "SN", "direction": -1 },
    { "id": 47, "text": { "fr": "Vos émotions vous contrôlent plus que vous ne les contrôlez.", "en": "Your emotions control you more than you control them." }, "dimension": "AT", "direction": -1 },
    { "id": 48, "text": { "fr": "Vous vous souciez davantage des sentiments des autres que de ce qui est logique.", "en": "You care more about others' feelings than about what is logical." }, "dimension": "TF", "direction": 1 },
    { "id": 49, "text": { "fr": "Votre style de travail est plus basé sur des impulsions d'énergie que sur un effort organisé.", "en": "Your work style is based more on energy bursts than organized effort." }, "dimension": "JP", "direction": -1 },
    { "id": 50, "text": { "fr": "Lorsque quelqu'un vous tient en haute estime, vous craignez de le décevoir.", "en": "When someone holds you in high regard, you fear disappointing them." }, "dimension": "AT", "direction": -1 },
    { "id": 51, "text": { "fr": "Vous aimeriez avoir un travail vous obligeant à travailler seul.", "en": "You would like a job that requires you to work alone." }, "dimension": "EI", "direction": -1 },
    { "id": 52, "text": { "fr": "Vous pensez que réfléchir à des questions philosophiques abstraites est une perte de temps.", "en": "You think pondering abstract philosophical questions is a waste of time." }, "dimension": "SN", "direction": -1 },
    { "id": 53, "text": { "fr": "Vous préférez les endroits animés aux lieux calmes et intimes.", "en": "You prefer busy places to quiet, intimate ones." }, "dimension": "EI", "direction": 1 },
    { "id": 54, "text": { "fr": "Si une décision vous semble juste, vous agissez sans besoin de preuves supplémentaires.", "en": "If a decision feels right, you act without needing further proof." }, "dimension": "TF", "direction": 1 },
    { "id": 55, "text": { "fr": "Vous vous sentez souvent submergé.", "en": "You often feel overwhelmed." }, "dimension": "AT", "direction": -1 },
    { "id": 56, "text": { "fr": "Vous terminez les tâches méthodiquement sans brûler les étapes.", "en": "You complete tasks methodically without skipping steps." }, "dimension": "JP", "direction": 1 },
    { "id": 57, "text": { "fr": "Vous préférez les tâches créatives aux tâches structurées.", "en": "You prefer creative tasks to structured ones." }, "dimension": "JP", "direction": -1 },
    { "id": 58, "text": { "fr": "Vous vous fiez davantage à votre intuition émotionnelle qu’à votre raisonnement logique.", "en": "You rely more on your emotional intuition than your logical reasoning." }, "dimension": "TF", "direction": 1 },
    { "id": 59, "text": { "fr": "Vous avez du mal à respecter les délais.", "en": "You struggle to meet deadlines." }, "dimension": "JP", "direction": -1 },
    { "id": 60, "text": { "fr": "Vous êtes confiant que les choses s'arrangeront pour vous.", "en": "You are confident that things will work out for you." }, "dimension": "AT", "direction": 1 }
];
